version: '3.2'
services:
  mongodb:
    build: ./mongodb
    volumes:
    - ./mongodb/data:/data/db/output
    ports:
    - ${MONGO_PORT}:27017
    env_file:
    - .env
    networks:
      mynet:
        ipv4_address: 172.28.2.1
  node1:
    build: ./python_blockchainapp
    ports:
    - 8001:8001
    command:
    - python
    - node_server.py
    - -p
    - '8001'
    networks:
      mynet:
        ipv4_address: 172.28.1.1
  node2:
    image: pythonblockchainapp_node1
    ports:
    - 8002:8002
    command:
    - python
    - node_server.py
    - -p
    - '8002'
    networks:
      mynet:
        ipv4_address: 172.28.1.2
  node3:
    image: pythonblockchainapp_node1
    ports:
    - 8003:8003
    command:
    - python
    - node_server.py
    - -p
    - '8003'
    networks:
      mynet:
        ipv4_address: 172.28.1.3
  node4:
    image: pythonblockchainapp_node1
    ports:
    - 8004:8004
    command:
    - python
    - node_server.py
    - -p
    - '8004'
    networks:
      mynet:
        ipv4_address: 172.28.1.4
  node5:
    image: pythonblockchainapp_node1
    ports:
    - 8005:8005
    command:
    - python
    - node_server.py
    - -p
    - '8005'
    networks:
      mynet:
        ipv4_address: 172.28.1.5
  node6:
    image: pythonblockchainapp_node1
    ports:
    - 8006:8006
    command:
    - python
    - node_server.py
    - -p
    - '8006'
    networks:
      mynet:
        ipv4_address: 172.28.1.6
  node7:
    image: pythonblockchainapp_node1
    ports:
    - 8007:8007
    command:
    - python
    - node_server.py
    - -p
    - '8007'
    networks:
      mynet:
        ipv4_address: 172.28.1.7
  node8:
    image: pythonblockchainapp_node1
    ports:
    - 8008:8008
    command:
    - python
    - node_server.py
    - -p
    - '8008'
    networks:
      mynet:
        ipv4_address: 172.28.1.8
  node9:
    image: pythonblockchainapp_node1
    ports:
    - 8009:8009
    command:
    - python
    - node_server.py
    - -p
    - '8009'
    networks:
      mynet:
        ipv4_address: 172.28.1.9
  node10:
    image: pythonblockchainapp_node1
    ports:
    - 8010:8010
    command:
    - python
    - node_server.py
    - -p
    - '8010'
    networks:
      mynet:
        ipv4_address: 172.28.1.10
  node11:
    image: pythonblockchainapp_node1
    ports:
    - 8011:8011
    command:
    - python
    - node_server.py
    - -p
    - '8011'
    networks:
      mynet:
        ipv4_address: 172.28.1.11
  node12:
    image: pythonblockchainapp_node1
    ports:
    - 8012:8012
    command:
    - python
    - node_server.py
    - -p
    - '8012'
    networks:
      mynet:
        ipv4_address: 172.28.1.12
  node13:
    image: pythonblockchainapp_node1
    ports:
    - 8013:8013
    command:
    - python
    - node_server.py
    - -p
    - '8013'
    networks:
      mynet:
        ipv4_address: 172.28.1.13
  node14:
    image: pythonblockchainapp_node1
    ports:
    - 8014:8014
    command:
    - python
    - node_server.py
    - -p
    - '8014'
    networks:
      mynet:
        ipv4_address: 172.28.1.14
  node15:
    image: pythonblockchainapp_node1
    ports:
    - 8015:8015
    command:
    - python
    - node_server.py
    - -p
    - '8015'
    networks:
      mynet:
        ipv4_address: 172.28.1.15
  node16:
    image: pythonblockchainapp_node1
    ports:
    - 8016:8016
    command:
    - python
    - node_server.py
    - -p
    - '8016'
    networks:
      mynet:
        ipv4_address: 172.28.1.16
  node17:
    image: pythonblockchainapp_node1
    ports:
    - 8017:8017
    command:
    - python
    - node_server.py
    - -p
    - '8017'
    networks:
      mynet:
        ipv4_address: 172.28.1.17
  node18:
    image: pythonblockchainapp_node1
    ports:
    - 8018:8018
    command:
    - python
    - node_server.py
    - -p
    - '8018'
    networks:
      mynet:
        ipv4_address: 172.28.1.18
  node19:
    image: pythonblockchainapp_node1
    ports:
    - 8019:8019
    command:
    - python
    - node_server.py
    - -p
    - '8019'
    networks:
      mynet:
        ipv4_address: 172.28.1.19
  node20:
    image: pythonblockchainapp_node1
    ports:
    - 8020:8020
    command:
    - python
    - node_server.py
    - -p
    - '8020'
    networks:
      mynet:
        ipv4_address: 172.28.1.20
networks:
  mynet:
    ipam:
      driver: default
      config:
      - subnet: 172.28.1.0/16
